# Introduction to NumPy

The Python programming language was not originally designed for numerical computing, but attracted the attention of the scientific and engineering community early on.

NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.

The NumPy documentation: https://numpy.org/doc/stable

In [3]:
# import the NumPy module and display the version number
import numpy as np
np.__version__

'1.26.4'

In [3]:
# Build-in documentation
# np.<TAB> in IPython
np?

Type:        module
String form: <module 'numpy' from 'C:\\Users\\ZXT3080\\anaconda3\\Lib\\site-packages\\numpy\\__init__.py'>
File:        c:\users\zxt3080\anaconda3\lib\site-packages\numpy\__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
 

In [5]:
# see the things in the np namespace
dir(np)

['ALLOW_THREADS',
 'BUFSIZE',
 'CLIP',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_builtins',
 '_core',
 '_distributor_init',


In [23]:
# Create a function to display the array attributes and data (optinally).  
#  Note the use of the default value for the show_data parameter.  Made
#  this part of the display optional (and off by default) to support large
#  arrays (that you wouldn't want to try to show explicitly)
def show(the_array, show_data = 0):
    print("  Dimension: {:}".format(the_array.ndim))
    print("       Size: {:}".format(the_array.size))
    print("      Shape: {:}".format(the_array.shape))    
    print("  Data Type: {:}".format(the_array.dtype))    
    print("  Item Size: {:}".format(the_array.itemsize))
    print("Data Buffer: {:}".format(the_array.data))
    if show_data:
        print("The data:")
        print(the_array)

print("Example function call:")
show(np.array([1, 2, 3, 4, 5]), 1)

Example function call:
  Dimension: 1
       Size: 5
      Shape: (5,)
  Data Type: int32
  Item Size: 4
Data Buffer: <memory at 0x0000017C06775A80>
The data:
[1 2 3 4 5]


## NumPy Arrays
### Creating Arrays and Accessing Elements

In [9]:
# Create a NumPy array from a list
a = np.array([1.5, 0.7, 22.4])
show(a, 1)

  Dimension: 1
       Size: 3
      Shape: (3,)
  Data Type: float64
  Item Size: 8
Data Buffer: <memory at 0x000002930D7FE740>
The data:
[ 1.5  0.7 22.4]


In [11]:
# Create a NumPy array from a list and specify the data type
a = np.array([1.5, 0.7, 22.4], dtype="int32")
show(a, 1)

  Dimension: 1
       Size: 3
      Shape: (3,)
  Data Type: int32
  Item Size: 4
Data Buffer: <memory at 0x000002930D7FE740>
The data:
[ 1  0 22]


In [13]:
# The second element (zero-based, so it's index 1)
a[1]

0

In [15]:
# Multi-dimensional array.  Note that NumPy arrays are homogenous -- all
#   elements are the same data type (dtype) -- integers in this case
b = np.array(
    [ [1,  2,  3,  4,   5]
     ,[6,  7,  8,  9,  10]
     ,[11, 12, 13, 14, 15] ] )
show(b, 1)

  Dimension: 2
       Size: 15
      Shape: (3, 5)
  Data Type: int32
  Item Size: 4
Data Buffer: <memory at 0x000002930DC7B440>
The data:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [21]:
# the (i, j)the element
i = 2
j = 4
b[i, j]

15

In [23]:
# Note that if one elements is a float, all will be upcast since
# NumPy arrays are homogeneous
b = np.array(
    [ [1.0,  2,  3,  4,   5]
     ,[6,  7,  8,  9,  10]
     ,[11, 12, 13, 14, 15] ] )
show(b,1)
# since Python lists are heterogeneous (in data types), there
# is no upcasting and a similar definition would have a list of lists
# with 1 float and the rest integers.

  Dimension: 2
       Size: 15
      Shape: (3, 5)
  Data Type: float64
  Item Size: 8
Data Buffer: <memory at 0x000002930DC7B2A0>
The data:
[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15.]]


In [25]:
# zeros function to create and array and initialize with zeros. Ones() works similarly.
# Note that you can also specify the data type.  Also note that with some
# datatype (e.g. float32), you seem to need to quote the type.
c = np.zeros((3, 8), dtype=int)
show(c, 1)

  Dimension: 2
       Size: 24
      Shape: (3, 8)
  Data Type: int32
  Item Size: 4
Data Buffer: <memory at 0x000002930DC7AE90>
The data:
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [31]:
# full() for arbitrary values
c = np.full((3, 8), 0)
show(c, 1)

  Dimension: 2
       Size: 24
      Shape: (3, 8)
  Data Type: int32
  Item Size: 4
Data Buffer: <memory at 0x000002930DC7A260>
The data:
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [33]:
# Create a NumPy array and initialize it with integers from 0 - 14 using
#   the arange(n) function.
a = np.arange(15)
show(a, 1)

  Dimension: 1
       Size: 15
      Shape: (15,)
  Data Type: int32
  Item Size: 4
Data Buffer: <memory at 0x000002930FEEE980>
The data:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [35]:
# Create the same array, but used floats and then reshape it to a 3x5 matrix (a 
#   2-dimensional array, technically)
a = np.arange(15, dtype=float)
show(a, 1)

  Dimension: 1
       Size: 15
      Shape: (15,)
  Data Type: float64
  Item Size: 8
Data Buffer: <memory at 0x000002930D7FE8C0>
The data:
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14.]


In [37]:
a = a.reshape(3,5)
show(a, 1)

  Dimension: 2
       Size: 15
      Shape: (3, 5)
  Data Type: float64
  Item Size: 8
Data Buffer: <memory at 0x000002930DC7BE00>
The data:
[[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]]


In [39]:
# Create a 20-element array of floats form 0 - 19 and reshape it to a 5x4 array.
# Note that we create an anonymous array and send that to
# the show() function.  The structure will be garbage-collected
# after the function call since it is anonymous.
show(np.arange(20.0).reshape(5,4), 1)

  Dimension: 2
       Size: 20
      Shape: (5, 4)
  Data Type: float64
  Item Size: 8
Data Buffer: <memory at 0x000002930DC79A40>
The data:
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]
 [16. 17. 18. 19.]]


In [41]:
# Use a comprehension - From VanderPlas
# Nested lists result in multi-dimensional arrays
n = np.array([range(i, i + 3) for i in [2, 4, 6]])
show(n, 1)

  Dimension: 2
       Size: 9
      Shape: (3, 3)
  Data Type: int32
  Item Size: 4
Data Buffer: <memory at 0x000002930DC7BD30>
The data:
[[2 3 4]
 [4 5 6]
 [6 7 8]]


In [43]:
# Show the details of what's going in the above assignment statement.
# First the inner comprehension
t = [range(i, i + 3) for i in [2, 4, 6]]
t

[range(2, 5), range(4, 7), range(6, 9)]

In [45]:
# Next create the NumPy array using the list created
# by the comprehension
np.array(t)

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [57]:
# Create a 3x3 array of normally distributed random values
# with mean 96 and standard deviation 14
c = np.random.normal(96, 14, (3, 3))
show(c, 1)

  Dimension: 2
       Size: 9
      Shape: (3, 3)
  Data Type: float64
  Item Size: 8
Data Buffer: <memory at 0x000002930FF69B10>
The data:
[[111.17142101 119.65397078 110.35215652]
 [ 83.08991149 107.50120033 125.26525841]
 [ 96.95581809  86.82448809  93.30189983]]


In [19]:
# Some more samples from VanderPlas
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

x1, x2, x3

(array([5, 0, 3, 3, 7, 9]),
 array([[3, 5, 2, 4],
        [7, 6, 8, 8],
        [1, 6, 7, 7]]),
 array([[[8, 1, 5, 9, 8],
         [9, 4, 3, 0, 3],
         [5, 0, 2, 3, 8],
         [1, 3, 3, 3, 7]],
 
        [[0, 1, 9, 9, 0],
         [4, 7, 3, 2, 7],
         [2, 0, 0, 4, 5],
         [5, 6, 8, 4, 1]],
 
        [[4, 9, 8, 1, 1],
         [7, 9, 9, 3, 6],
         [7, 2, 0, 3, 5],
         [9, 4, 4, 6, 4]]]))

In [25]:
# Iterating through a Python list of NumPy arrays.
al = [x1, x2, x3]
for a in al:
    show(a, 1)
    print("")

  Dimension: 1
       Size: 6
      Shape: (6,)
  Data Type: int32
  Item Size: 4
Data Buffer: <memory at 0x0000017C066CFF40>
The data:
[5 0 3 3 7 9]

  Dimension: 2
       Size: 12
      Shape: (3, 4)
  Data Type: int32
  Item Size: 4
Data Buffer: <memory at 0x0000017C040F0930>
The data:
[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]

  Dimension: 3
       Size: 60
      Shape: (3, 4, 5)
  Data Type: int32
  Item Size: 4
Data Buffer: <memory at 0x0000017C032046D0>
The data:
[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]



In [35]:
# Element (1, 2, 3) from x3
x3[2, 1, 3]

3

In [37]:
# flatten a multi-dimensional array
show(x3.flatten(), 1)

  Dimension: 1
       Size: 60
      Shape: (60,)
  Data Type: int32
  Item Size: 4
Data Buffer: <memory at 0x0000017C066CFF40>
The data:
[8 1 5 9 8 9 4 3 0 3 5 0 2 3 8 1 3 3 3 7 0 1 9 9 0 4 7 3 2 7 2 0 0 4 5 5 6
 8 4 1 4 9 8 1 1 7 9 9 3 6 7 2 0 3 5 9 4 4 6 4]


In [39]:
# NumPy arrays are mutable.
print(x2[0,0])
x2[0,0] = 12
x2

3


array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [45]:
# Note the behavior when we try to assign a different data type ...
print(x2[0, 1])
x2[0, 1] = 7.325
show(x2, 1)

5
  Dimension: 2
       Size: 12
      Shape: (3, 4)
  Data Type: int32
  Item Size: 4
Data Buffer: <memory at 0x0000017C038EF510>
The data:
[[12  7  2  4]
 [ 7  7  8  8]
 [ 1  6  7  7]]


### More on reshaping and np.newaxis

The concept of "axes" is one of the more confusing aspects of NumPy.  Axes are used throughout the NumPy-based ecosystem -- notebly for us Pandas and Matplotlib, so you need to know them.  Lots and lots of online material.  I found this one particularly easy to understand - https://www.sharpsightlabs.com/blog/numpy-axes-explained/

In [ ]:
x = np.array([1, 2, 3])
x, show(x)

In [ ]:
# What is the difference between x and y?
y = x.reshape((1,3))
y

In [ ]:
# What is the difference between y and z?
z = x.reshape((3,1))
z

In [ ]:
x.shape, y.shape,z.shape

In [ ]:
y[0]

In [ ]:
x[np.newaxis, :]

In [ ]:
x[:,np.newaxis]

In [ ]:
a = np.arange(27).reshape((3,3,3))
a

In [ ]:
a = np.arange(81).reshape((3,3,3,3))
a

 ### Slices - Views and copies
 
 Slice: [i:j:k] - start:stop:stride (for each axis)

In [47]:
# Show the 2D array x2
x2

array([[12,  7,  2,  4],
       [ 7,  7,  8,  8],
       [ 1,  6,  7,  7]])

In [49]:
# slice example - upper-left 2x3 sub-matrix
# :2 - rows 0, 1
# :3 - columns 0, 1, 2
x2[:2, :3]

array([[12,  7,  2],
       [ 7,  7,  8]])

In [51]:
# lower right 2x3
x2[-2:, -3:]

array([[7, 8, 8],
       [6, 7, 7]])

In [53]:
# middle 1x2
x2[1:-1, 1:-1]

array([[7, 8]])

In [55]:
# note that slices are (by default) views of the array, not copies.
x = x2[:2, :3]
x, x2

(array([[12,  7,  2],
        [ 7,  7,  8]]),
 array([[12,  7,  2,  4],
        [ 7,  7,  8,  8],
        [ 1,  6,  7,  7]]))

In [57]:
x[0, 0] = 477
x, x2

(array([[477,   7,   2],
        [  7,   7,   8]]),
 array([[477,   7,   2,   4],
        [  7,   7,   8,   8],
        [  1,   6,   7,   7]]))

In [59]:
# If you want a copy, rather than a view, use the copy() function.
x = x2[:2, :3].copy()
x[0, 0] = 976
x, x2

(array([[976,   7,   2],
        [  7,   7,   8]]),
 array([[477,   7,   2,   4],
        [  7,   7,   8,   8],
        [  1,   6,   7,   7]]))

## Array Concatenation and Splitting - VP 02.02

## Universal Functions and the Slowness of Loops - VP 02.03

## Axes and Aggregate Functions

Also check notebook 02.04 - Aggregations: Min, Max, and Everything Inbetween from Vanderplas

In [61]:
a = np.random.normal(5, 1, (5, 3))
show(a, 1)

  Dimension: 2
       Size: 15
      Shape: (5, 3)
  Data Type: float64
  Item Size: 8
Data Buffer: <memory at 0x0000017C0678A330>
The data:
[[6.25441407 6.41910204 4.25614392]
 [2.4825629  3.49290398 6.14907613]
 [3.80642175 6.14104245 6.50944508]
 [6.06777513 4.31341052 5.01487332]
 [4.6243341  4.96177636 5.36797447]]


In [63]:
# Overall sum -- all elements of the array
a.sum()

75.861256210341

In [65]:
# Sum along an axis -- What is axis 0?
a.sum(axis=0)

array([23.23550795, 25.32823535, 27.29751291])

In [67]:
# Sum along the other axis -- What is axis 1
a.sum(axis=1)

array([16.92966003, 12.124543  , 16.45690928, 15.39605897, 14.95408494])

In [69]:
# the average of the 3rd column
a.mean(axis=0)[2]

5.459502582996934

In [71]:
# or - we can sum along an axis and then divide by the
# number of elements along that axis.
ax = 0
a.sum(axis=ax)[2]/a.shape[ax]

5.459502582996934

In [73]:
# How did that work now?  Look at the components individually
a.sum(axis=ax)

array([23.23550795, 25.32823535, 27.29751291])

In [75]:
a.shape

(5, 3)

In [77]:
# average of the 4th row
a.mean(axis=1)[3]

5.132019656109631

In [79]:
# or
ax = 1
a.sum(axis=ax)[3]/a.shape[ax]

5.132019656109631

In [81]:
b = np.random.randint(1, 6, (3, 4, 6))
show(b, 1)

  Dimension: 3
       Size: 72
      Shape: (3, 4, 6)
  Data Type: int32
  Item Size: 4
Data Buffer: <memory at 0x0000017C032046D0>
The data:
[[[4 3 2 3 4 4]
  [4 3 4 5 2 3]
  [4 2 3 2 5 3]
  [4 1 4 3 4 1]]

 [[1 1 4 3 4 1]
  [5 1 1 3 4 3]
  [4 1 1 1 4 1]
  [3 3 1 5 4 5]]

 [[1 5 4 4 5 2]
  [4 1 1 1 2 1]
  [5 2 4 2 1 1]
  [5 4 4 2 1 1]]]


In [83]:
# Mean of the "planes"
b.mean(axis=0)

array([[2.        , 3.        , 3.33333333, 3.33333333, 4.33333333,
        2.33333333],
       [4.33333333, 1.66666667, 2.        , 3.        , 2.66666667,
        2.33333333],
       [4.33333333, 1.66666667, 2.66666667, 1.66666667, 3.33333333,
        1.66666667],
       [4.        , 2.66666667, 3.        , 3.33333333, 3.        ,
        2.33333333]])

In [ ]:
# Mean of the ?
b.mean(axis=1)

In [ ]:
# Mean of the ?
b.mean(axis=2)

## Example with A Dataset from a CSV file

In [ ]:
# erv.csv data - a (100x15 matrix of floats)
erv = np.genfromtxt('..\data\erv.csv', delimiter=',')
show(erv)

In [ ]:
# show a sample - upper left 5x5 (first five columns of the first 5 rows)
for r in erv[:5, :5]:
    print(r)

In [ ]:
# Use the aggregate sum to find the column averages in one statement.
erv.mean(axis=0)

In [ ]:
# row averages
erv.mean(axis=1)

In [ ]:
# Load matplotlib
%matplotlib inline
import matplotlib.pyplot as plt

In [ ]:
# Show a histogram of the jth column (j between 0 and 14)
j = 9
plt.hist(erv[:,j])
plt.show()

In [ ]:
# show histograms of all 15 columns in a single plot
plt.figure(figsize=(20, 8))
for j in range(1, 16):
    plt.subplot(3,5,j)
    plt.hist(erv[:,j-1])
plt.show()

In [ ]:
# or with color
c = ['orange', 'green', 'red', 'beige', 'brown'
    ,'dimgray', 'firebrick', 'darkkhaki', 'indigo', 'darksalmon'
    ,'forestgreen', 'fuchsia', 'darkcyan', 'darkviolet','darkgoldenrod'
    ]
plt.figure(figsize=(20, 8))
for j in range(15):
    plt.subplot(3,5,j+1)
    plt.hist(erv[:,j], color=c[j])
plt.show()

In [ ]:
# Scatter plot of column col1 vs column col2
col1 = 0
col2 = 14
plt.scatter(erv[:, col1], erv[:, col2]);

In [ ]:
plt.scatter?